edition = "2024"
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true